version: "3.8"

services:
  jenkins:
    build: .
    container_name: jenkins_custom
    ports:
      - "8080:8080"      # Jenkins UI
      - "50000:50000"    # Agent port
    volumes:
      - jenkins_data:/var/jenkins_home
    restart: unless-stopped

volumes:
  jenkins_data: