# .github/workflows/lint.yml
name: Lint Code Base

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  call-super-linter:
    name: Call Super-Linter
    runs-on: ubuntu-latest
    permissions:
      contents: read
      statuses: write

    uses: bretfisher/super-linter-workflow/.github/workflows/reusable-super-linter.yaml@main
    with:
      devops-only: true
      filter-regex-exclude: ".*compose-sample-3/html/.*,.*dockerfile-sample-5/.*"
    env:
      # IMPORTANT: This makes Super-Linter not exit with failure even if it finds errors.
      DISABLE_ERRORS: "true"